from 	ubuntu 

WORKDIR /app

COPY 	requirements.txt requirements.txt

RUN	apt-get update -y \
	&& apt-get install -y python3 \
	&& apt-get install -y python3-pip\
	&& apt-get install -y python3-flask \
	&& pip install -r requirements.txt

ENV 	FLASK_APP=application.py

EXPOSE 	8080

COPY 	. /app

CMD	['echo', 'building first docker container']
CMD 	['flask', 'run']

